export const VESSELS = [
  {
    name: 'BRA',
    day: 1,
    title: 'BRA GERMANY',
    start: 8,
    end: 14,
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    color: '#ccc',
    dragPosition: { x: 0, y: 70 },
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'BRA2',
    day: 1,
    title: 'BRA GERMANY',
    start: 8,
    end: 14,
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    color: '#ccc',
    dragPosition: { x: -89, y: 70 },
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'IRA',
    day: 1,
    title: 'IRA GERMANY',
    start: 14,
    end: 20,
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    color: '#007bff',
    dragPosition: { x: -178, y: 70 },
    offsetTop: 0,
    offsetLeft: 0,
  },
  {
    name: 'EMP',
    day: 1,
    title: 'EMP GERMANY',
    start: 20,
    end: 23,
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    color: 'red',
    // dragPosition: { x: -153, y: 0 },
    dragPosition: { x: -276, y: 70 },

    offsetTop: 47,
    offsetLeft: 663,
  },
  {
    name: 'MIA',
    day: 1,
    title: 'MIA GERMANY',
    start: 20,
    end: 23,
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    color: 'purple',
    dragPosition: { x: 0, y: 70 },
    offsetTop: 0,
    offsetLeft: 0,
  },
  {
    name: 'MIA2',
    day: 1,
    title: 'MIA GERMANY',
    start: 8,
    end: 23,
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    color: 'green',
    dragPosition: { x: 0, y: 0 },
    offsetTop: 100,
    offsetLeft: 200,
  },
];
