import {
  startOfDay,
  endOfDay,
  subDays,
  addDays,
  endOfMonth,
  isSameDay,
  isSameMonth,
  addHours,
  getHours,
} from 'date-fns';

export const VESSELS = [
  {
    name: 'BRA',
    day: 1,
    title: 'BRA GERMANY',
    start: subDays(startOfDay(new Date()), 1),
    end: addDays(new Date(), 1),
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: '#FAE3E3',
    border: '#FF9C9C',
    dragPosition: { x: 0, y: 70 },
    gridRowStart: 2,
    gridRowEnd: 3,
    gridColumnStart: 3,
    gridColumnEnd: 18,
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'BRA',
    day: 1,
    title: 'BRA GERMANY',
    start: subDays(endOfMonth(new Date()), 3),
    end: addDays(endOfMonth(new Date()), 3),
    size: 1000,
    width: 65,
    heigth: 36,
    color: '#D1E8FF',
    border: '#85C2FF',
    bow: false,
    dragPosition: { x: 0, y: 70 },
    gridRowStart: 3,
    gridRowEnd: 4,
    gridColumnStart: 5,
    gridColumnEnd: 10,
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'BRA2',
    day: 1,
    title: 'BRA GERMANY',
    start: subDays(endOfMonth(new Date()), 3),
    end: addDays(endOfMonth(new Date()), 3),
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: '#FDF1BA',
    border: '#FFE570',
    dragPosition: { x: -89, y: 70 },
    gridRowStart: 4,
    gridRowEnd: 5,
    gridColumnStart: 6,
    gridColumnEnd: 12,
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'IRA',
    day: 1,
    title: 'IRA GERMANY',
    start: addHours(startOfDay(new Date()), 2),
    end: addHours(new Date(), 2),
    size: 1000,
    bow: false,
    width: 65,
    heigth: 36,
    color: '#BBFCD1',
    border: '#43FF72',
    dragPosition: { x: -178, y: 70 },
    offsetTop: 0,
    offsetLeft: 0,
    gridRowStart: 6,
    gridRowEnd: 12,
    gridColumnStart: 4,
    gridColumnEnd: 8,
  },
  {
    name: 'EMP',
    day: 1,
    title: 'EMP GERMANY',
    start: addHours(startOfDay(new Date()), 2),
    end: addHours(new Date(), 2),
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: '#FFA294',
    border: '#FC4528',
    dragPosition: { x: -276, y: 70 },
    offsetTop: 47,
    offsetLeft: 663,
    gridRowStart: 16,
    gridRowEnd: 18,
    gridColumnStart: 9,
    gridColumnEnd: 18,
  },
  {
    name: 'MIA',
    day: 1,
    title: 'MIA GERMANY',
    start: addHours(startOfDay(new Date()), 2),
    end: addHours(new Date(), 2),
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    bow: false,
    color: '#CB94FF',
    border: '#5D3780',
    dragPosition: { x: 0, y: 70 },
    offsetTop: 0,
    offsetLeft: 0,
    gridRowStart: 5,
    gridRowEnd: 9,
    gridColumnStart: 17,
    gridColumnEnd: 18,
  },
  {
    name: 'MIA2',
    day: 1,
    title: 'MIA GERMANY',
    start: addHours(startOfDay(new Date()), 2),
    end: addHours(new Date(), 2),
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: '#BFFF99',
    border: '#76FC28',
    dragPosition: { x: 0, y: 0 },
    offsetTop: 100,
    offsetLeft: 200,
    gridRowStart: 21,
    gridRowEnd: 23,
    gridColumnStart: 12,
    gridColumnEnd: 13,
  },
];
