export const VESSELS = [
  {
    name: 'BRA',
    day: 1,
    title: 'BRA GERMANY',
    start: 8,
    end: 14,
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: '#ccc',
    dragPosition: { x: 0, y: 70 },
    gridRowStart: 2,
    gridRowEnd: 3,
    gridColumnStart: 3,
    gridColumnEnd: 18,
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'BRA',
    day: 1,
    title: 'BRA GERMANY',
    start: 8,
    end: 14,
    size: 1000,
    width: 65,
    heigth: 36,
    color: 'yellow',
    bow: false,
    dragPosition: { x: 0, y: 70 },
    gridRowStart: 3,
    gridRowEnd: 4,
    gridColumnStart: 5,
    gridColumnEnd: 10,
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'BRA2',
    day: 1,
    title: 'BRA GERMANY',
    start: 8,
    end: 14,
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: 'blue',
    dragPosition: { x: -89, y: 70 },
    gridRowStart: 4,
    gridRowEnd: 5,
    gridColumnStart: 6,
    gridColumnEnd: 12,
    // offsetTop: 100,
    // offsetLeft: 100,
  },
  {
    name: 'IRA',
    day: 1,
    title: 'IRA GERMANY',
    start: 14,
    end: 20,
    size: 1000,
    bow: false,
    width: 65,
    heigth: 36,
    color: '#007bff',
    dragPosition: { x: -178, y: 70 },
    offsetTop: 0,
    offsetLeft: 0,
    gridRowStart: 6,
    gridRowEnd: 12,
    gridColumnStart: 4,
    gridColumnEnd: 8,
  },
  {
    name: 'EMP',
    day: 1,
    title: 'EMP GERMANY',
    start: 20,
    end: 23,
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: 'red',
    dragPosition: { x: -276, y: 70 },
    offsetTop: 47,
    offsetLeft: 663,
    gridRowStart: 16,
    gridRowEnd: 18,
    gridColumnStart: 9,
    gridColumnEnd: 18,
  },
  {
    name: 'MIA',
    day: 1,
    title: 'MIA GERMANY',
    start: 20,
    end: 23,
    size: 1000,
    orientation: 'izq',
    width: 65,
    heigth: 36,
    bow: false,
    color: 'purple',
    dragPosition: { x: 0, y: 70 },
    offsetTop: 0,
    offsetLeft: 0,
    gridRowStart: 5,
    gridRowEnd: 9,
    gridColumnStart: 17,
    gridColumnEnd: 18,
  },
  {
    name: 'MIA2',
    day: 1,
    title: 'MIA GERMANY',
    start: 8,
    end: 23,
    size: 1000,
    bow: true,
    width: 65,
    heigth: 36,
    color: 'green',
    dragPosition: { x: 0, y: 0 },
    offsetTop: 100,
    offsetLeft: 200,
    gridRowStart: 21,
    gridRowEnd: 23,
    gridColumnStart: 12,
    gridColumnEnd: 13,
  },
];
